### ISSUE TITLE
doesn't work anymore on recent official r39 kernal release

### ISSUE THREAD

**Issue by irmen** [JimmyDansbo/vtuilib#1]
Vera memory layout has been changed I think that's the reason VTUI no longer works 
https://github.com/commanderx16/x16-rom/issues/185#issuecomment-1080470516

**Comment by JimmyDansbo** [comment]
I will have a look at fixing it asap. Hopefully I will have time to during this weekend.

**Comment by JimmyDansbo** [comment]
Library has been upgraded to version 0.9 to support X16 R39
