### ISSUE TITLE
Please add source to the binary "VTUIx.x.BIN" as source code "VTUIx.x.ASM", including resources, please?

### ISSUE THREAD

**Issue by TheRealHamtaro126** [JimmyDansbo/vtuilib#2]
There is a problem, This is not the complete source code. There is missing code for the main library named "VTUIx.x.BIN". That is a problem for me wanting any modifications to the code. The question is: Is it possible for a request to accept people the right to modify this code?

Hope you can resolve this. Thank you for your time.

**Comment by JimmyDansbo** [comment]
If you have a look at the build.sh script, you will see that all that is used to build VTUIx.x.BIN is vtuilib-generic.asm, all of the code is in that single file. The rest of the files are just examples.
