### ISSUE TITLE
Small problems with Input

### ISSUE THREAD

**Issue by mgkaiser** [JimmyDansbo/vtuilib#3]
1) The cursor can go 1 step beyond the length of the string
2) The results seem to be padded with $00 if the full string is not used.  Consider padding with spaces or allowing the padding character to be chosen.
3) If you provide a non-empty buffer, the first character of the buffer is destroyed and should be retained.  If you simply press enter the previous value should be left unmodified.  Currently the first character is destroyed.
4) Left and right arrow should allow you to move in the string.
5) I believe that 3 and 4 are cause by using a block character as the cursor.  Consider instead simply reversing the foreground and background colors as a cursor.

**Comment by JimmyDansbo** [comment]
I have just pushed https://github.com/JimmyDansbo/VTUIlib/commit/03d0e86ec33db92e6f7833a6a7f1582f532dca63 which solves number 2 and 3.

Regarding number 1, I actually like it better that the cursor moves beyond the line length. The alternative would be that the final character entered was inverted?

Number 4 sounds like a feature request, I will look into it, but I am not sure I can fit it below the 1KB limit.

**Comment by JimmyDansbo** [comment]
I am unable to fit the functionality of item number 4 within the 1KB limit I have set for the VTUI library. - Feel free to create a pull request if you figure out how to implement it.
