### ISSUE TITLE
Handle `<esc>` in `vtui_input_str` as a special key/custom handler?

### ISSUE THREAD

**Issue by oodler577** [JimmyDansbo/vtuilib#4]
Hi @JimmyDansbo, your library has inspired me to attempt to create a `vi` clone. I am at the very early stages, but am trying to figure out how to detect and handle when the `<esc>` key is hit while `vtui_input_str` is actively consuming key strokes. I am also using `prog8`.

I tried setting a `KEYHDL` handler, but I don't think that's working. I am learning to read asm better, but very much a high level programmer. I did read the `vtui_input_str` code and saw you handle `<return>` and `<backspace>`.

What I think I need for `<esc>` is:

1. exit like `<return>`, but no newline
2. goto a custom routine (in my case I am going into a new state where keyboard input will be used for commands or navigation)

While I can imagine this being more of a generic solution, I wanted to be as specific as possible to you so you can give me some advice or offer this kind of a thing via VTUI. Thank you! (I am on discord in `#prog8` usually)

**Comment by JimmyDansbo** [comment]
It is trivial to handle ESC key in the input_str function and I would change it to actually return the last key pressed in .A
That way it will be possible for you own program to check whether the function exited because return or esc was pressed.
Can you think of other keys that should be handled in a similar way?

**Comment by oodler577** [comment]
I'd certainly defer to you here and would learn to use whatever you provide. I can't think of any other key that would need to be special in a `vi` clone during _insert_ mode. Thank you!

**Comment by JimmyDansbo** [comment]
I have just pushed https://github.com/JimmyDansbo/VTUIlib/commit/c1c7ee64715ec76ff7e6c4566de959c8ee3c0ea8 which allows input_str function to exit on ESC
